# Generated by Django 3.0.2 on 2020-02-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=70)),
                ('mobile', models.IntegerField()),
                ('address1', models.TextField(blank=True, null=True)),
                ('address2', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=15)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'User Description',
            },
        ),
    ]
